server:
  port: 8089
  servlet:
    context-path: /firstapp

spring:
  redis:
    host: 192.168.1.13
    port: 6379
    password: null
    database: 0

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.url=jdbc:mysql://192.168.1.13:3306/testCache
#spring.datasource.username=root
#spring.datasource.password=mysql
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
